services:
  - type: web
    name: marimekko-app
    runtime: python
    buildCommand: pip install -r requirements.txt && curl -fsSL -o NotoSansJP.otf "https://github.com/google/fonts/raw/main/ofl/notosansjp/NotoSansJP%5Bwght%5D.ttf"
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
